<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:variable name="initial_bottom_pos">27.5</xsl:variable>
	<xsl:variable name="initial_left_pos">0.5</xsl:variable>
	<xsl:variable name="height_increment">1.7</xsl:variable>
	<xsl:variable name="width_increment">7</xsl:variable>
	<xsl:variable name="frame_height">1.7cm</xsl:variable>
	<xsl:variable name="frame_width">6.0cm</xsl:variable>
	<xsl:variable name="number_columns">3</xsl:variable>
	<xsl:variable name="max_frames">51</xsl:variable>

	<xsl:template match="/">
		<xsl:apply-templates select="lots"/>
	</xsl:template>

	<xsl:template match="lots">
		<document>
			<template showBoundary="0" leftMargin="2.0cm" rightMargin="2.0cm" topMargin="2.0cm" bottomMargin="2.0cm" title="Etiquetas productos" author="Generated by nanoAPPs">
				<!-- showBoundary="1" -->
				<pageTemplate id="all">
					<pageGraphics/>
					<xsl:apply-templates select="lot-line" mode="frames"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<paraStyle name="nospace" fontName="Arial" fontSize="6" spaceBefore="0" spaceAfter="5"/>
				<paraStyle name="nospacex" fontName="Arial" fontSize="6" spaceBefore="-9" spaceAfter="0"/>
				<paraStyle name="nospacec" fontName="Arial" fontSize="6" spaceBefore="-2" spaceAfter="0"/>
				<paraStyle name="nospaceb" fontName="Arial" fontSize="6" spaceBefore="0" spaceAfter="0" leftIndent="0.5cm"/>
				<blockTableStyle id="mytable">
					<blockAlignment value="CENTER"/>
					<blockValign value="MIDDLE"/>
					<!-- lineStyle kind="GRID" colorName="black" tickness="1"/ -->
				</blockTableStyle>
			</stylesheet>
			<story>
				<xsl:apply-templates select="lot-line" mode="story"/>
			</story>
		</document>
	</xsl:template>

	<xsl:template match="lot-line" mode="frames">
		<xsl:if test="position() &lt; $max_frames + 1">
			<frame>
				<xsl:attribute name="width">
					<xsl:value-of select="$frame_width"/>
				</xsl:attribute>
				<xsl:attribute name="height">
					<xsl:value-of select="$frame_height"/>
				</xsl:attribute>
				<xsl:attribute name="x1">
					<xsl:value-of select="$initial_left_pos + ((position()-1) mod $number_columns) * $width_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
				<xsl:attribute name="y1">
					<xsl:value-of select="$initial_bottom_pos - floor((position()-1) div $number_columns) * $height_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
			</frame>
		</xsl:if>
	</xsl:template>

    <xsl:param name="pmaxChars" as="xs:integer" select="28"/>

	<xsl:template match="lot-line" mode="story">
		<blockTable style="mytable" colWidths="4.5cm,1.2cm">
			<tr>
				<td>
					<para style="nospace"><xsl:value-of select="substring(product, 1, $pmaxChars)"/></para>
					<para style="nospacex"><xsl:value-of select="substring(product, $pmaxChars + 1, $pmaxChars - 1)"/></para>
					<para style="nospacec"><xsl:value-of select="code"/></para>
				</td>
				<td>
					<barCode code="code128"><xsl:value-of select="barcode" /></barCode>
					<para style="nospaceb"><xsl:text>      </xsl:text><xsl:value-of select="barcode"/></para>
				</td>
			</tr>
		</blockTable>
		<xsl:if test="position() &lt; last()">
			<nextFrame/>
		</xsl:if>
	</xsl:template>
</xsl:stylesheet>
